#!/usr/bin/env python3
"""
Build a redaction spec for the documentation screenshots.

Regions are placed from the actual pixels of each 720x1280 capture. They are
generous rows rather than tight glyph boxes: a box that misses by a few pixels
would leave part of the server address readable, and a full row reads as a
deliberate redaction.

Light and dark captures share the app's layout, so each screen's regions are
applied to both (SSH/terminal screenshots exist only in the terminal's own
dark palette).

Usage:  python3 scripts/redaction_spec.py           # writes /tmp/opencode/redact/spec.txt
        java Redact /tmp/opencode/redact/spec.txt   # applies it in place
"""
import os

IMG = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "docs", "images")

# The app's top bar as it appears on screens that name the server or the SSH
# connection (the server label, and "user@address" on SSH screens).
TOPBAR = (55, 58, 500, 78)

# screen -> (needs_topbar, [(x, y, w, h), ...])
SCREENS = {
    # Rows are full-width (x 30..690) on purpose: a box that starts a few pixels
    # right of the text leaves the first letter or digit readable, and the
    # sensitive values here are all on rows of their own.
    #
    # Welcome header: "Hello, <user>" + the account email.
    "02-dashboard": (False, [(18, 60, 420, 74), (30, 915, 660, 120)]),
    # Card label + plan line, then the primary address.
    # The Linodes *list* top bar says "Linodes", not the server, so no topbar box.
    "03-linodes": (False, [(30, 275, 660, 82), (30, 412, 660, 30)]),
    # "Linode ID" value and the attached firewall's name (right-aligned values).
    "04-linode-detail": (True, [(400, 918, 300, 30), (400, 1225, 300, 30)]),
    # Public IPv4 + reverse-DNS name, then the IPv6 addresses.
    "05-linode-network": (True, [(30, 480, 660, 125), (30, 633, 660, 200)]),
    "06-linode-metrics": (True, []),
    "07-linode-storage": (True, []),
    "08-linode-manage": (True, []),
    "09-create-linode": (False, []),
    "10-volumes": (False, []),
    # The firewall card: name, rule summary and attached-Linode chip.
    "11-network": (False, [(30, 260, 660, 170)]),
    "12-network-domains": (False, []),        # empty state, nothing to hide
    # Header title and the label field both hold the firewall name.
    "13-firewall-editor": (True, [(70, 282, 570, 40)]),
    # Username + email, then the device key name and fingerprint.
    "14-account": (False, [(150, 178, 400, 72), (100, 897, 520, 68)]),
    # Device key, profile key, and the support-ticket title with its number.
    "15-account-appearance": (False, [(100, 226, 520, 68), (100, 537, 520, 62), (40, 733, 630, 70)]),
    # The SSH form: address, username and the selected device key.
    "16-ssh-setup": (True, [(70, 268, 580, 38), (70, 388, 320, 38), (70, 718, 320, 36)]),
    # The last-login line (source address) and the shell prompt (user@host).
    "17-terminal": (True, [(0, 155, 720, 26), (0, 448, 720, 36), (0, 476, 340, 34)]),
    "18-terminal-sessions": (True, [(0, 155, 720, 26), (0, 448, 720, 36), (0, 476, 340, 34)]),
    # The SFTP sheet's remote path.
    "19-upload": (True, [(0, 155, 720, 26), (85, 560, 400, 40)]),
    # The log's "connecting to <address>" line and "authenticated as <user>".
    "20-session-log": (True, [(0, 155, 720, 130), (95, 468, 500, 60), (95, 585, 500, 30)]),
    "21-terminal-opencode": (True, []),
    # Prompt, working directory and the subscription line.
    "22-terminal-claude": (True, [(0, 146, 700, 94)]),
}

SKIP = {"01-login", "icon", "icon-variants"}


def main():
    lines = ["# Redaction spec for docs/images (generated by scripts/redaction_spec.py)",
             "# format: image path, then one 'x y w h' per line"]
    n_regions = n_images = 0
    for name in sorted(os.listdir(IMG)):
        if not name.endswith(".png"):
            continue
        stem = name[:-4]
        base = stem[:-5] if stem.endswith("-dark") else stem
        if base in SKIP or base not in SCREENS:
            continue
        wants_topbar, content = SCREENS[base]
        regions = ([TOPBAR] if wants_topbar else []) + list(content)
        if not regions:
            continue
        lines.append(os.path.join(IMG, name))
        n_images += 1
        for (x, y, w, h) in regions:
            lines.append(f"{x} {y} {w} {h}")
            n_regions += 1
    with open("/tmp/opencode/redact/spec.txt", "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"{n_regions} regions across {n_images} images")


if __name__ == "__main__":
    main()
